### ISSUE TITLE
Reactive events for clicks and others

### ISSUE THREAD

**Issue by green-nick** [tarasantoshchuk/Architecture#4]
Rename `Null.INSTANCE` for click events to `Void.VOID` for example.

**Comment by tarasantoshchuk** [comment]
@green-nick 
[documentation](https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#nulls) sugests that we use shared 

`enum Irrelevant { INSTANCE; }`

**Comment by tarasantoshchuk** [comment]
`Null.INSTANCE` removed in https://github.com/tarasantoshchuk/Architecture/commit/56afb2d3713dda632071343a1a0dc0318516b298
as library doesn't use it anyway
